version: "3.8"

services:
  backup:
    build:
      context: .
      dockerfile: Dockerfile
    user: "1002:1001"
    volumes:
      - ./config:/config
      - ./sourcetest:/source
      - ./targettest:/target
    restart: unless-stopped
