version: "3.8"

services:
  backup:
    image: ghcr.io/lucasrui/neo-nas:latest
    user: "1002:1001"
    volumes:
      - ./config:/config
      - ./sourcetest:/source
      - ./targettest:/target
    restart: unless-stopped
