version: "3.8"

services:
  backup:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./testbackup/config:/config
      - ./testbackup:/testbackup
    restart: unless-stopped
